stages:
- name: Build
  steps:
  - runScriptConfig:
    image: registry.cn-hangzhou.aliyuncs.com/fullj/aliyun-maven:3-jdk-8
    shellScript: |-
      mvn --settings /settings.xml clean package
- name: Publish
  steps:
  - publishImageConfig:
    dockerfilePath: ./Dockerfile
    buildContext: .
    tag: pipeline-example-spring:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
    path: ./deployment.yaml
